name: Deploy
on:
  workflow_run:
    workflows: ['Lint and Test']
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        run: echo "${{ toJSON(github) }}"
